on:
  push:
    branches:
      - main
    paths:
      - resume/*

jobs:
  resume:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v3
      - name: "build"
        run: |
          cd resume
          ./build.sh github
      - name: "commit changes"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add resume.pdf
          git commit -m "Updated resume at $(date)"
          git push origin main
